//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SERIESREMINDER.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatCorreo
    {
        public int IDCorreo { get; set; }
        public string Correo { get; set; }
        public bool Estado { get; set; }
    }
}
