//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SERIESREMINDER.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConfigCorreo
    {
        public int IDConfig { get; set; }
        public string correo { get; set; }
        public string contrasena { get; set; }
        public string host { get; set; }
        public int puerto { get; set; }
        public int hora { get; set; }
        public int minutos { get; set; }
    }
}
