//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SERIESREMINDER.Models
{
    using System;
    
    public partial class credencialesCorreo_Result1
    {
        public string Correo { get; set; }
        public string Contrasena { get; set; }
        public string Host { get; set; }
        public Nullable<int> Port { get; set; }
        public Nullable<int> Hora { get; set; }
        public Nullable<int> Minutos { get; set; }
    }
}
