//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SERIESREMINDER.Models
{
    using System;
    
    public partial class seriesDia_Result1
    {
        public int IDSerie { get; set; }
        public string nombreSerie { get; set; }
        public string resumenSerie { get; set; }
        public string posterPath { get; set; }
        public string Estado { get; set; }
        public int cantTemporadas { get; set; }
        public System.DateTime ultimoEpisodio { get; set; }
        public System.DateTime proximoEpisodio { get; set; }
    }
}
